
trigger:
- main

pool:
  vmImage: ubuntu-latest

Jobs:
- job: Init
  steps:
  - script: echo Init!
    displayName: 'Run a one-line script'
- job: Validate
  steps: 
  - script: echo Validate!
    displayName: 'Run a multi-line script'
